version: '3'
services:

# Local S3 Alternative
  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9010:9010"
      - "9011:9011"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    command: server --address :9010 --console-address :9011 /data

#  metabase-app:
#    image: metabase/metabase
#    restart: always
#    ports:
#      - 3001:3000
#    volumes:
#      # declare your mount volume /host/dir:/container/dir
#      - ./metabase-data:/metabase-data



# TRINO
  trino:
    image: "trinodb/trino:432"
    volumes:
      - ./docker/trino/etc:/usr/lib/trino/etc:ro
      - ./docker/trino/catalog:/etc/trino/catalog
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/trino/catalog/bigquery.json

    ports:
      - "8081:8080"
      - "8889:8889"

## HIVE METASTORE
  mariadb:
    image: mariadb:10.11.2
    ports:
      - 3306:3306
    command: "--log-bin --max_connections=1000 --max_user_connections=1000"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  metastore:
    build: .
    image: hive-metastore:latest
    restart: unless-stopped
    container_name: metastore
    hostname: metastore
    volumes:
      - ./beeline:/home/hive/.beeline
      - ./scripts/hive/conf:/opt/hive/conf
    environment:
      - SERVICE_NAME=metastore
      - IS_RESUME=true
      - DB_DRIVER=mysql
    ports:
    - 9083:9083
    depends_on:
      - mariadb

  hiveserver2:
    build: .
    image: hive-metastore:latest
    restart: unless-stopped
    container_name: hiveserver2
    volumes:
      - ./scripts/hive/conf:/opt/hive/conf
    environment:
      - SERVICE_NAME=hiveserver2
      - HIVE_SERVER2_THRIFT_PORT = 10000
      - IS_RESUME=true
      - DB_DRIVER=mysql
      - SERVICE_OPTS = '-Xmx1G -Dhive.metastore.uris=thrift://metastore:9083'
    ports:
    - 10000:10000
    - 10002:10002
    depends_on:
      - metastore

networks:
  default:
    name: myNetwork
    driver: bridge



