version: '3'
services:


# LOCALIZED SPARK CONTAINER (For Experimental Push into S3/Minio)
#   spark-master:
#     image: bitnami/spark:3.3-debian-11
#     container_name: spark-master
#     command: /opt/bitnami/spark/sbin/start-thriftserver.sh
#     ports:
#       - 8088:8080
#       - 7077:7077
#       - 10000:10000
#     volumes:
#       - ./spark-workspace:/opt/workspace
#       - ./scripts/metastore-site.xml:/opt/bitnami/spark/conf/hive-site.xml

#   spark-worker-1:
#     image: bitnami/spark:3.3-debian-11
#     container_name: spark-worker-1
#     environment:
#       - SPARK_WORKER_CORES=1
#       - SPARK_WORKER_MEMORY=512m
#     ports:
#       - 8081:8081
#     volumes:
#       - ./spark-workspace:/opt/workspace
#     depends_on:
#       - spark-master
#   spark-worker-2:
#     image: bitnami/spark:3.3-debian-11
#     container_name: spark-worker-2
#     environment:
#       - SPARK_WORKER_CORES=1
#       - SPARK_WORKER_MEMORY=512m
#     ports:
#       - 8082:8081
#     volumes:
#       - ./spark-workspace:/opt/workspace
#     depends_on:
#       - spark-master


# ## PINOT 

#   pinot-zookeeper:
#     image: zookeeper:3.5.6
#     platform: linux/amd64
#     container_name: pinot-zookeeper
#     ports:
#       - "2181:2181"
#     environment:
#       ZOOKEEPER_CLIENT_PORT: 2181
#       ZOOKEEPER_TICK_TIME: 2000

#   pinot-controller:
#     image: apachepinot/pinot:0.9.3
#     platform: linux/amd64
#     command: "StartController -zkAddress pinot-zookeeper:2181"
#     container_name: pinot-controller
#     restart: unless-stopped
#     ports:
#       - "9000:9000"
#     environment:
#       JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms1G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-controller.log"
#     depends_on:
#       - pinot-zookeeper

#   pinot-broker:
#     image: apachepinot/pinot:0.9.3
#     platform: linux/amd64
#     command: "StartBroker -zkAddress pinot-zookeeper:2181"
#     restart: unless-stopped
#     container_name: "pinot-broker"
#     ports:
#       - "8099:8099"
#     environment:
#       JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx4G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-broker.log"
#     depends_on:
#       - pinot-controller

#   pinot-server:
#     image: apachepinot/pinot:0.9.3
#     platform: linux/amd64
#     command: "StartServer -zkAddress pinot-zookeeper:2181"
#     restart: unless-stopped
#     container_name: "pinot-server"
#     ports:
#       - "8098:8098"
#     environment:
#       JAVA_OPTS: "-Dplugins.dir=/opt/pinot/plugins -Xms4G -Xmx16G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Xloggc:gc-pinot-server.log"
#     depends_on:
#       - pinot-broker


# Local S3 Alternative
  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9010:9010"
      - "9011:9011"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    command: server --address :9010 --console-address :9011 /data

#  metabase-app:
#    image: metabase/metabase
#    restart: always
#    ports:
#      - 3001:3000
#    volumes:
#      # declare your mount volume /host/dir:/container/dir
#      - ./metabase-data:/metabase-data



# TRINO
  trino:
    image: "trinodb/trino:406"
    volumes:
      - ./docker/trino/etc:/usr/lib/trino/etc:ro
      - ./docker/trino/catalog:/etc/trino/catalog
    ports:
      - "8080:8080"


## HIVE METASTORE

  mariadb:
    image: mariadb:10.11.2
    ports:
      - 3306:3306
    command: "--log-bin --max_connections=1000 --max_user_connections=1000"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    build: .
    image: hive-metastore:latest
    ports:
    - 9083:9083
    depends_on:
      - mariadb

networks:
  default:
    name: myNetwork
    driver: bridge



