version: '3'
services:

# Local S3 Alternative
  minio:
    image: minio/minio
    hostname: minio
    ports:
      - "9010:9010"
      - "9011:9011"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
    command: server --address :9010 --console-address :9011 /data

  metabase-app:
    image: metabase/metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      # declare your mount volume /host/dir:/container/dir
      - ./metabase-data:/metabase-data



# TRINO
  trino:
    image: "trinodb/trino:432"
    volumes:
      - ./docker/trino/etc:/usr/lib/trino/etc:ro
      - ./docker/trino/catalog:/etc/trino/catalog
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /etc/trino/catalog/bigquery.json

    ports:
      - "8080:8080"
      - "8889:8889"

## HIVE METASTORE
  mariadb:
    image: mariadb:10.11.2
    ports:
      - 3306:3306
    command: "--log-bin"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db

  hive-metastore:
    build: .
    image: hive-metastore:latest
    ports:
    - 9083:9083
    depends_on:
      - mariadb

networks:
  default:
    name: myNetwork
    driver: bridge



